#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo TheSkyX Install dir not exist
    exit 1
fi

cp "/tmp/IIDC_X2/cameralist IIDC.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp "/tmp/IIDC_X2/IIDCCamSelect.ui" "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/"
cp "/tmp/IIDC_X2/IIDCCamera.ui" "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/"
cp "/tmp/IIDC_X2/libIIDC.dylib" "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/cameralist IIDC.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/IIDCCamSelect.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/IIDCCamera.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/CameraPlugIns/libIIDC.dylib"
fi

rm -rf /tmp/IIDC_X2

